Updates for `3.9.4` release
stripe/stripe-terminal-android pull request #509
Opened 2024-09-20 15:58 UTC by ugochukwu-stripe

2024-09-20 16:01 UTC, usaimbhayat-stripe approved these changes

2024-09-20 17:02 UTC, xiaoshen-stripe requested changes
Make it clear that it is impacting handoff mode

2024-09-20 17:02 UTC, xiaoshen-stripe commented on CHANGELOG.md
> +### Handoff
```suggestion
### Apps on Devices: Handoff mode
```

2024-09-23 21:35 UTC, ebarrenechea-stripe approved these changes

2024-09-23 21:35 UTC, merged